spec:
  inputs:
    stage:
      default: 'release'
---
release:package:
  image: registry.moselwal.io/devops/images/php/$PHP_VERSION/ci
  stage: $[[ inputs.stage ]]
  rules:
    - if: $CI_COMMIT_TAG != null
      when: always
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'